package enums;

public enum PlayerState {
	GAME_SARTING, WAITING_FOR_GAMESTART, BUILDING_VILLAGE, BUILDING_STREET, DICEROLLING,
	DISPENDE_CARDS_ROBBER_LOSS, MOVE_ROBBER, TRADING_OR_BUILDING, WAITING, CONNECTION_LOST, 
	
	//OLD enums for debugging only
	TRADING, OFFERING, PLAYING
}
